[2022-11-08 17:11:35 +0900] [898] [INFO] Starting gunicorn 20.1.0
[2022-11-08 17:11:35 +0900] [898] [INFO] Listening at: http://0.0.0.0:8000 (898)
[2022-11-08 17:11:35 +0900] [898] [INFO] Using worker: sync
[2022-11-08 17:11:35 +0900] [900] [INFO] Booting worker with pid: 900
[2022-11-08 17:11:35 +0900] [900] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/big/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/big/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/big/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/big/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/big/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/big/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/big/.local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2022-11-08 17:11:35 +0900] [900] [INFO] Worker exiting (pid: 900)
[2022-11-08 17:11:35 +0900] [898] [INFO] Shutting down: Master
[2022-11-08 17:11:35 +0900] [898] [INFO] Reason: Worker failed to boot.
[2022-11-17 14:24:39 +0900] [22332] [INFO] Starting gunicorn 20.1.0
[2022-11-17 14:24:39 +0900] [22332] [INFO] Listening at: http://0.0.0.0:8000 (22332)
[2022-11-17 14:24:39 +0900] [22332] [INFO] Using worker: sync
[2022-11-17 14:24:39 +0900] [22334] [INFO] Booting worker with pid: 22334
{'ip': '172.17.0.1', 'user': 'AnonymousUser', 'http_method': 'GET', 'url': '/', 'parameter': {}, 'timestamp': 1668662687, 'session_id': 'None'}
